### ISSUE TITLE
Inconsistencies in Themes??

### ISSUE THREAD

**Issue by DavidFW1960** [JuanMTech/ios_dark_mode_theme#1]
Hi Juan,

I have quite a lot of themes installed in my home assistant... I like change lol... But just a question (not an issue as such with your themes)

I am specifically wondering about the use of 2 variables.

Specifically:
```
paper-item-icon-color: rgb(174, 174, 178)
state-icon-color: rgb(10, 132, 255)
```
Under what circumstances would you select either of those variables? Why are they set to a different colour? What happens in my lovelace is this:

![image](https://user-images.githubusercontent.com/36390762/89745972-6175a300-dafa-11ea-80be-5456922b57b9.png)

The 2 icons on the left are the standard inbuilt button-card and the one on the right is the custom-button-card.
I'm pretty sure the inbuilt cards are using the state-icon-color They are just buttons for a switch but the right hand one is an input_boolean which doesn't have a colour by default and needs to have color set by css or by an option on the card. (this is just an example but I have others) So in my lovelace I have standardised on mapping input boolean colour using the state-icon-color and state-icon-active-color variable and for most themes this seems to work however your themes are using a different color for the above 2 variables. I guess I'm wondering why? Particularly given the paper-item ones are all going to be deprecated (many have already been) but I don't understand why you are using different colours in those variables?

**Comment by JuanMTech** [comment]
That's the way I wanted to have it.
