### ISSUE TITLE
Rename theme

### ISSUE THREAD

**Issue by basnijholt** [JuanMTech/ios_dark_mode_theme#2]
Hi @JuanMTech,

Nice that you made this theme! I would like to ask whether you could rename the themes into something that doesn't exist yet.

It will now give a lot of confusion because of the iOS Dark Mode Theme.

![image](https://user-images.githubusercontent.com/6897215/89768202-98988400-dafb-11ea-8e81-90a344eb0459.png)

**Comment by JuanMTech** [comment]
No. The other themes available are based into HomeKit than the actual iOS dark or light mode.
