### ISSUE TITLE
Gauge Card problems with RED

### ISSUE THREAD

**Issue by cobch** [JuanMTech/ios_dark_mode_theme#3]
Hi,

I never get the red color working in the gauge card when using the dark och light IOS theme. Could you please fix that? Se pictures below.

Ios Light Mode (or another dark mode):
![image](https://user-images.githubusercontent.com/50397676/93689661-e0ce9d00-fad0-11ea-843b-357a40aba819.png)

When I choose the default theme from HA:
![image](https://user-images.githubusercontent.com/50397676/93689671-0360b600-fad1-11ea-8f42-1f828596679e.png)

**Comment by JuanMTech** [comment]
The above is not from this iOS Light mode theme.
